export const DETERMINE_BORDER = "DETERMINE_BORDER";
export const FIX_CENTER = "FIX_CENTER";
export const ADD_LOCATION = "ADD_LOCATION";
export const REMOVE_LOCATION = "REMOVE_LOCATION";
export const REMOVE_ALL_LOCATIONS = 'REMOVE_ALL_LOCATIONS';
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const CHANGE_OPEN = "CHANGE_OPEN";
export const DELETE_MODAL = "DELETE_MODAL";